name: docker-build-action
description: docker-build-action
inputs:
  path_dockerfile:
    description: "path_dockerfile"
    required: false
    default: "Dockerfile"
  image_name:
    description: "image_name"
    required: true
  tag_name:
    description: "tag_name"
    required: false
runs:
  using: composite
  steps:
    - name: Docker Build image
      run: |
        if [ -z "${{ inputs.tag_name }}" ]; then
            export TAG=$(date +%s)
        else
            export TAG="${{ inputs.tag_name }}"
        fi
        docker build . --file ${{ inputs.path_dockerfile }} --tag ${{inputs.image_name}}:$TAG
      shell: bash