name: docker-push
description: docker-push
inputs:
  docker_username:
    description: "docker username"
    required: false
  docker_image:
    description: "docker image"
    required: false
  image_tag:
    description: "original docker image tag"
    required: false
runs:
  using: composite
  steps:
    - name: tag image
      run: docker image tag ${{inputs.docker_image}}:${{inputs.image_tag}} ${{inputs.docker_username}}/${{inputs.docker_image}}:${{inputs.image_tag}}
      shell: bash
    - name: tag image
      run: docker image push ${{inputs.docker_username}}/${{inputs.docker_image}}:${{inputs.image_tag}}
      shell: bash